### ISSUE TITLE
Support for Printer Options

### ISSUE THREAD

**Issue by eggplants** [pecigonzalo/pre-commit-shfmt#7]
ref: #3 

```shellsession
$ shfmt -version
3.4.3
$ shfmt -h
usage: shfmt [flags] [path ...]
...
Printer options:

  -i uint   indent: 0 for tabs (default), >0 for number of spaces
  -bn       binary ops like && and | may start a line
  -ci       switch cases will be indented
  -sr       redirect operators will be followed by a space
  -kp       keep column alignment paddings
  -fn       function opening braces are placed on a separate line
...
```

**Comment by pecigonzalo** [comment]
Hey @eggplants, your issue/comment prompted me to update this, and I've made it use `shfmt` directly, which now allows passing all args and removes the `-P` grep flag.

This should make the hook a lot more flexible, and likely this can be closed as well as #3 #6

**Comment by eggplants** [comment]
You have removed an entry script and changed into `language: system`. It means manual installation of shfmt is required and this project's hook is not working on pre-commit CI now, is it? That's so unwanted changes for me...

**Comment by eggplants** [comment]
Please add the tips to README:

```text
manual installation of shfmt is required before running.
```

**Comment by pecigonzalo** [comment]
The wrapper script was just a wrapper before as well, manual installation
was always required.
Was this not the case for you?

**Comment by eggplants** [comment]
Oh, I didn't notice it. But I think it is better to use the hook of #8 than present system hook.

**Comment by pecigonzalo** [comment]
Both have it's palace, I think the other one would be a nice addition as
well.
